# Generated by Django 6.0.3 on 2026-04-01 10:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_article_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletranslation',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='articletranslation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.article', verbose_name='Maqola'),
        ),
    ]
