# Generated by Django 6.0.3 on 2026-04-01 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_articletranslation_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ru', 'Ruscha'), ('en', 'Inglizcha')], max_length=10)),
                ('name', models.CharField(max_length=150, verbose_name='Tarjima nomi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='news.category')),
            ],
            options={
                'db_table': 'categorytranslation',
                'unique_together': {('category', 'language')},
            },
        ),
    ]
